### PR TITLE
add stuff for Zip file reading and writing.

### LINKED ISSUE #1: add .nimble file
thanks for the work on this library.
I'd like to use this library to support .zip files without requiring the .so like the one in nim/zip/zipfiles.
could you add a .nimble file to the repo?
It looks like someone already registered another, less complete "miniz" package but it could still be installed by nimble with the full URL.

### PR DESCRIPTION
**Pull request by brentp**
closes #1

### CODE REVIEW

**Comment by brentp** [comment]
I believe this is ready. I hit some problems using it in my code in odd cases (though it's not directly clear it's from this library, I think that it is).
On gitter, it was suggested that it could be because this wrapper was not using e.g. `cdecl` calling conventions or `bycopy` on the object.

**Comment by h3rald** [comment]
Wow thank you so much for this!

I'll do some testing and see if it doesn't break anything in my min programming language that depends on it, and then merge it and release it.

**Comment by h3rald** [comment]
Another question... why did you specify version "0.2.5"? I don't think I ever released a version of this wrapper, although I used it in my min language. 

We could release it as 1.0.0 perhaps, I don't think the API is gonna change much either.

**Comment by brentp** [comment]
0.2.5 was the version of the software from which I copied the contents of the .nimble file.
please change as you like.

**Pull request merged**
